name       : budgie-caffeine-applet
version    : 0.1.5
release    : 3
source     :
    - https://github.com/yursan9/budgie-caffeine-applet/archive/v0.1.5.tar.gz : ea95017e3eb3b0cd7f2e7fb33ed31870de7e1f058d57d44bbd22be461b0129e1
license    : GPL-2.0
component  : desktop.budgie
summary    : Budgie Caffeine Applet
description: |
    Simple applet to prevent screen dimming on long idle time.
builddeps  :
    - pkgconfig(budgie-1.0)
rundeps    :
    - libnotify
    - python3-gobject
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
