name       : budgie-caffeine-applet
version    : 0.1.3
release    : 1
source     :
    - https://github.com/yursan9/budgie-caffeine-applet/archive/v0.1.3.tar.gz : fbbc82119a33d519d61b61d822d8a993893cffd7284f8c692f6e59a518a405c4
license    : GPL-2.0
component  : desktop.budgie
summary    : Budgie Caffeine Applet
description: |
    Simple applet to prevent screen dimming on long idle time.
builddeps  :
    - pkgconfig(budgie-1.0)
rundeps    :
    - libnotify
    - python3-gobject
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install

    install -Dm 00644 data/com.github.yursan9.budgie-caffeine-applet.appstream.xml \
    $installdir/usr/share/metainfo/com.github.yursan9.budgie-caffeine-applet.appstream.xml
